### ISSUE TITLE
Will there be support for a more complete player? or...

### ISSUE THREAD

**Issue by ospfranco** [kadiks/react-native-itunes#5]
How about moving forward, backward? or is there any way I can reproduce the file in a different player?

**Comment by ospfranco** [comment]
I just took a look at the code and found this:
```

    // NSNumber *persistentId = [RCTConvert NSNumber:trackItem[@"persistentId"]];
    NSString *searchTitle = [trackItem objectForKey:@"title"];
    NSString *searchAlbumTitle = [trackItem objectForKey:@"albumTitle"];
    
    if (searchTitle != nil) {
        
        MPMediaQuery *songQuery = [[MPMediaQuery alloc] init];
        
        
        [songQuery addFilterPredicate:[MPMediaPropertyPredicate predicateWithValue:searchTitle forProperty: MPMediaItemPropertyTitle comparisonType:MPMediaPredicateComparisonContains]];
        [songQuery addFilterPredicate:[MPMediaPropertyPredicate predicateWithValue:searchAlbumTitle forProperty:MPMediaItemPropertyAlbumTitle comparisonType:MPMediaPredicateComparisonContains]];
        
```

This seems to be easily breakable, instead of handling the reproduction may I suggest returning a url and letting other library handle the reproduction, this seems a more general approach :)

**Comment by kadiks** [comment]
Very good question: I actually don't know.
The main goal of the library is to retrieve data.

Now, I see where having a player might come handy.

Of course, my first goal was to get a url as you suggested, but as far as I remember, Apple Music did not return one for offline songs (don't know for iTunes songs from your own library).

To answer your question, the long term vision is to move forward with a player. But the short/mid term is to stay as is until it is more stable. So I'll leave this issue open for anyone who comes with an idea that will either:

- help to have a complete player
- help to extract url for offline and online tracks (preferred solution)

Thanks for your contributions ;)

EDIT :

Because you load songs from your own library, have you tried the field: `assetUrl`? It's already part of the current library.
Looking at this, it should be ok for your case: https://www.reddit.com/r/iOSProgramming/comments/3d3id9/songs_saved_offline_from_apple_music_have_no_url/

**Comment by themakerman** [comment]
@kadiks So finally i found something that can work for me. Just to get things clear! This library searches for music files stored/synced in itunes folder right? I just want to retrieve list of files[path/album_art/title....] as array so that i can render them using listView for iOS devices. Is this possible?

**Comment by kadiks** [comment]
@themakerman Correct. Retrieving information about your iTunes/Apple Music library.

You can also play songs, but this is not the main goal here.

Note: the path will be filled only for songs you bought. Songs in your Apple Music cache will not display a path.

**Comment by themakerman** [comment]
@kadiks You mention in your note that I can only get path to music files I have bought via iTunes. What about music files that I have synced from my MacBook? Won't I be able to access them using this library? Besides this for playing music I am using native module.

**Comment by kadiks** [comment]
@themakerman Yes, those too.

Let me clarify:

- You will see all the details of every music that appear in iTunes/Apple Music all combined (so music that you sync are coming from iTunes, which works too).
- Special case for the `assetUrl` (or "path" as you call it) will be non-null only if you actually own it: either by buying them on iTunes or by syncing them and have the actual source file.

**Comment by themakerman** [comment]
@kadiks Great. Thank you so much. Will be using your library in an production App. Would really appreciate your help in future in case i am unable to somehow use this library. Will be trying it in a few days time. Good day.

**Comment by kadiks** [comment]
It's been open long enough for suggestions and I decided this library will not support player capabilities.

**Comment by peterfalbo** [comment]
Forgive me, I'm net to React-Native. I have been trying to get this working with my app for the past few days and I just can't get it to work. I get build errors even when I install it in a clean app. 

`React/RCTBridgeModule.h` file not found

Am I missing something in the installation instructions?
